// Generated by gencpp from file assistant_robin/Activate.msg
// DO NOT EDIT!


#ifndef ASSISTANT_ROBIN_MESSAGE_ACTIVATE_H
#define ASSISTANT_ROBIN_MESSAGE_ACTIVATE_H

#include <ros/service_traits.h>


#include <assistant_robin/ActivateRequest.h>
#include <assistant_robin/ActivateResponse.h>


namespace assistant_robin
{

struct Activate
{

typedef ActivateRequest Request;
typedef ActivateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Activate
} // namespace assistant_robin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assistant_robin::Activate > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::assistant_robin::Activate&) { return value(); }
};

template<>
struct DataType< ::assistant_robin::Activate > {
  static const char* value()
  {
    return "assistant_robin/Activate";
  }

  static const char* value(const ::assistant_robin::Activate&) { return value(); }
};


// service_traits::MD5Sum< ::assistant_robin::ActivateRequest> should match 
// service_traits::MD5Sum< ::assistant_robin::Activate > 
template<>
struct MD5Sum< ::assistant_robin::ActivateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assistant_robin::Activate >::value();
  }
  static const char* value(const ::assistant_robin::ActivateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assistant_robin::ActivateRequest> should match 
// service_traits::DataType< ::assistant_robin::Activate > 
template<>
struct DataType< ::assistant_robin::ActivateRequest>
{
  static const char* value()
  {
    return DataType< ::assistant_robin::Activate >::value();
  }
  static const char* value(const ::assistant_robin::ActivateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assistant_robin::ActivateResponse> should match 
// service_traits::MD5Sum< ::assistant_robin::Activate > 
template<>
struct MD5Sum< ::assistant_robin::ActivateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assistant_robin::Activate >::value();
  }
  static const char* value(const ::assistant_robin::ActivateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assistant_robin::ActivateResponse> should match 
// service_traits::DataType< ::assistant_robin::Activate > 
template<>
struct DataType< ::assistant_robin::ActivateResponse>
{
  static const char* value()
  {
    return DataType< ::assistant_robin::Activate >::value();
  }
  static const char* value(const ::assistant_robin::ActivateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSISTANT_ROBIN_MESSAGE_ACTIVATE_H
