// Generated by gencpp from file speech_recog_uc/DOAResult.msg
// DO NOT EDIT!


#ifndef SPEECH_RECOG_UC_MESSAGE_DOARESULT_H
#define SPEECH_RECOG_UC_MESSAGE_DOARESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech_recog_uc
{
template <class ContainerAllocator>
struct DOAResult_
{
  typedef DOAResult_<ContainerAllocator> Type;

  DOAResult_()
    : angle(0.0)  {
    }
  DOAResult_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::speech_recog_uc::DOAResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_recog_uc::DOAResult_<ContainerAllocator> const> ConstPtr;

}; // struct DOAResult_

typedef ::speech_recog_uc::DOAResult_<std::allocator<void> > DOAResult;

typedef boost::shared_ptr< ::speech_recog_uc::DOAResult > DOAResultPtr;
typedef boost::shared_ptr< ::speech_recog_uc::DOAResult const> DOAResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_recog_uc::DOAResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_recog_uc::DOAResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speech_recog_uc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'speech_recog_uc': ['/home/alf/catkin_ws/src/speech_recog_uc/speech_recog_uc/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_recog_uc::DOAResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_recog_uc::DOAResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_recog_uc::DOAResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::speech_recog_uc::DOAResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_recog_uc/DOAResult";
  }

  static const char* value(const ::speech_recog_uc::DOAResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n\
";
  }

  static const char* value(const ::speech_recog_uc::DOAResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DOAResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_recog_uc::DOAResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_recog_uc::DOAResult_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_RECOG_UC_MESSAGE_DOARESULT_H
